/**
 * generated by Xtext
 */
package com.sandy.xtext.validation;

import com.sandy.xtext.validation.AbstractJoveNotesValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class JoveNotesValidator extends AbstractJoveNotesValidator {
}
