/*
 * generated by Xtext
 */
package com.sandy.xtext;

import org.eclipse.xtext.parser.IEncodingProvider;
import org.eclipse.xtext.service.DispatchingProvider;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JoveNotesRuntimeModule extends com.sandy.xtext.AbstractJoveNotesRuntimeModule {

    public void configureRuntimeEncodingProvider(Binder binder) {
        binder.bind(IEncodingProvider.class)
        .annotatedWith(DispatchingProvider.Runtime.class)
        .to( UTF8EncodingProvider.class );
    }
}
