/*
 * generated by Xtext
 */
package com.sandy.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JoveNotesStandaloneSetup extends JoveNotesStandaloneSetupGenerated{

	public static void doSetup() {
		new JoveNotesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

