/*
 * generated by Xtext
 */
package com.sandy.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.sandy.xtext.services.JoveNotesGrammarAccess;

public class JoveNotesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private JoveNotesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.sandy.xtext.parser.antlr.internal.InternalJoveNotesParser createParser(XtextTokenStream stream) {
		return new com.sandy.xtext.parser.antlr.internal.InternalJoveNotesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "JoveNotes";
	}
	
	public JoveNotesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JoveNotesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
